%% Search for a specified operating point for the model - main_to_linearize.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 25.2 and Simulink Control Design (TM) 25.2.
%
% Generated on: 26-Jan-2026 20:25:26

%% Specify the model name
model = 'main_to_linearize';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - main_to_linearize/Drone Dynamics/6DOF (Quaternion)/Calculate DCM & Euler Angles/q0 q1 q2 q3
% - Default model initial conditions are used to initialize optimization.

% State (2) - main_to_linearize/Drone Dynamics/6DOF (Quaternion)/p,q,r
% - Default model initial conditions are used to initialize optimization.
opspec.States(2).SteadyState = [true;false;false];

% State (3) - main_to_linearize/Drone Dynamics/6DOF (Quaternion)/ub,vb,wb
% - Default model initial conditions are used to initialize optimization.

% State (4) - main_to_linearize/Drone Dynamics/6DOF (Quaternion)/xe,ye,ze
% - Default model initial conditions are used to initialize optimization.

% State (7) - main_to_linearize/Drone Dynamics/Actuator Dynamics/bx_actuator_resp
% - Default model initial conditions are used to initialize optimization.

% State (8) - main_to_linearize/Drone Dynamics/Actuator Dynamics/by_actuator_resp
% - Default model initial conditions are used to initialize optimization.

% State (9) - main_to_linearize/Drone Dynamics/Actuator Dynamics/motor_thrus_resp_bot
% - Default model initial conditions are used to initialize optimization.

% State (10) - main_to_linearize/Drone Dynamics/Actuator Dynamics/motor_thrust_resp
% - Default model initial conditions are used to initialize optimization.

% State (11) - main_to_linearize/Subsystem2/Integrator
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
